# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StockMarketAgent < Formula
  desc "AI-powered stock market update agent for Telegram"
  homepage "https://github.com/Technology-Institute/homebrew-stock-market-agent"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Technology-Institute/homebrew-stock-market-agent/releases/download/v1.0.0/homebrew-stock-market-agent_1.0.0_darwin_amd64.tar.gz"
      sha256 "f8e551bfa9a0c30382e8a14944324f447443a946717326930704c4c929a7948f"

      def install
        bin.install "stock-market-agent"
        etc.install "config.yaml" => "stock-market-agent/config.yaml"
        etc.install ".sample-env" => "stock-market-agent/.sample-env"
        etc.install "setup-cron.sh" => "stock-market-agent/setup-cron.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Technology-Institute/homebrew-stock-market-agent/releases/download/v1.0.0/homebrew-stock-market-agent_1.0.0_darwin_arm64.tar.gz"
      sha256 "9f84352a4462d75cb7af0d9f897f4ba180586c0cb422b2ee62538f2d9cd1db19"

      def install
        bin.install "stock-market-agent"
        etc.install "config.yaml" => "stock-market-agent/config.yaml"
        etc.install ".sample-env" => "stock-market-agent/.sample-env"
        etc.install "setup-cron.sh" => "stock-market-agent/setup-cron.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Technology-Institute/homebrew-stock-market-agent/releases/download/v1.0.0/homebrew-stock-market-agent_1.0.0_linux_amd64.tar.gz"
      sha256 "7151beef8072d5359da43af5822bdbe8e29ff84162cd19bb5fe9e13dd0bf2dd8"
      def install
        bin.install "stock-market-agent"
        etc.install "config.yaml" => "stock-market-agent/config.yaml"
        etc.install ".sample-env" => "stock-market-agent/.sample-env"
        etc.install "setup-cron.sh" => "stock-market-agent/setup-cron.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Technology-Institute/homebrew-stock-market-agent/releases/download/v1.0.0/homebrew-stock-market-agent_1.0.0_linux_arm64.tar.gz"
      sha256 "8e5c1a71753ad8cf396b710d32daef8bab99c1333c10b90929a16a504c8e50c7"
      def install
        bin.install "stock-market-agent"
        etc.install "config.yaml" => "stock-market-agent/config.yaml"
        etc.install ".sample-env" => "stock-market-agent/.sample-env"
        etc.install "setup-cron.sh" => "stock-market-agent/setup-cron.sh"
      end
    end
  end

  test do
    system "#{bin}/stock-market-agent", "--version"
  end
end
